export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS"
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL"
export const GET_ALL_USER_LOADING = "GET_ALL_USER_LOADING"

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"

export const DELETE_APPOINMENT_USER_SUCCESS = "DELETE_APPOINMENT_USER_SUCCESS"
export const DELETE_APPOINMENT_USER_FAIL = "DELETE_APPOINMENT_USER_FAIL"

export const DELETE_POST_USER_SUCCESS = "DELETE_POST_USER_SUCCESS"
export const DELETE_POST_USER_FAIL = "DELETE_POST_USER_FAIL"

export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAIL = "GET_USER_FAIL"
