export const POST_APPOINTMENT_SUCCESS = 'POST_APPOINTMENT_SUCCESS';
export const POST_APPOINTMENT_FAIL = 'POST_APPOINTMENT_FAIL';

export const GET_ONE_APPOINTMENT_SUCCESS = 'GET_ONE_APPOINTMENT_SUCCESS';
export const GET_ONE_APPOINTMENT_FAIL = 'GET_ONE_APPOINTMENT_FAIL';
export const GET_ONE_APPOINTMENT_LOADING = 'GET_ONE_APPOINTMENT_LOADING';

export const GET_LAWYER_APPOINTMENT_SUCCESS = 'GET_LAWYER_APPOINTMENT_SUCCESS';
export const GET_LAWYER_APPOINTMENT_FAIL = 'GET_LAWYER_APPOINTMENT_FAIL';
export const GET_LAWYER_APPOINTMENT_LOADING = 'GET_LAWYER_APPOINTMENT_LOADING';

export const GET_APPOINTMENTS_SUCCESS = 'GET_APPOINTMENTS_SUCCESS';
export const GET_APPOINTMENTS_FAIL = 'GET_APPOINTMENTS_FAIL';
export const GET_APPOINTMENTS_LOADING = 'GET_APPOINTMENTS_LOADING';

export const DEL_APPOINTMENT_SUCCESS = 'DEL_APPOINTMENT_SUCCESS';
export const DEL_APPOINTMENT_FAIL = 'DEL_APPOINTMENT_FAIL';

export const CONFIRM_APPOINTMENT_SUCCESS = 'CONFIRM_APPOINTMENT_SUCCESS';
export const CONFIRM_APPOINTMENT_FAIL = 'CONFIRM_APPOINTMENT_FAIL';