export const REGISTER_SUCCESS = "REGISTER_SUCCESS" 
export const REGISTER_FAIL = "REGISTER_FAIL" 
export const REGISTER_LOADING = "REGISTER_LOADING"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS" 
export const LOGIN_FAIL = "LOGIN_FAIL" 
export const LOGIN_LOADING = "LOGIN_LOADING"

export const FORGOT_PASSWORD_LOADING = "FORGOT_PASSWORD_LOADING"
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL"

export const RESET_PASSWORD_LOADING = "RESET_PASSWORD_LOADING"
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL"

export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const GET_CURRENT_USER_FAIL = "GET_CURRENT_USER_FAIL";

export const LOGOUT  = "LOGOUT"

