export const POST_PROFILE_SUCCESS = "POST_PROFILE_SUCCESS"
export const POST_PROFILE_FAIL = "POST_PROFILE_FAIL"

export const GET_PROFILES_SUCCESS = "GET_PROFILES_SUCCESS"
export const GET_PROFILES_FAIL = "GET_PROFILES_FAIL"
export const GET_PROFILES_LOADING = "GET_PROFILES_LOADING"

export const GET_ONE_PROFILE_SUCCESS = "GET_ONE_PROFILE_SUCCESS"
export const GET_ONE_PROFILE_FAIL = "GET_ONE_PROFILE_FAIL"
export const GET_ONE_PROFILE_LOADING = "GET_ONE_PROFILE_LOADING"

export const GET_My_PROFILE_SUCCESS = "GET_My_PROFILE_SUCCESS"
export const GET_My_PROFILE_FAIL = "GET_My_PROFILE_FAIL"
export const GET_My_PROFILE_LOADING = "GET_My_PROFILE_LOADING"

export const DEL_PROFILE_SUCCESS = "DEL_PROFILE_SUCCESS"
export const DEL_PROFILE_FAIL = "DEL_PROFILE_SUCCESS"