export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';
export const GET_USER_LOADING = 'GET_USER_LOADING';

export const PUT_USER_SUCCESS = 'PUT_USER_SUCCESS';
export const PUT_USER_FAIL = 'PUT_USER_SUCCESS';

export const DEL_USER_SUCCESS = 'DEL_USER_SUCCESS';
export const DEL_USER_FAIL = 'DEL_USER_FAIL';